### ISSUE TITLE
Make `<li>` a normal `ContainerType`

### ISSUE THREAD

**Issue by etam** [skubalj/build_html#10]
The current special case for lists (see https://github.com/skubalj/build_html/blob/v2.4.0/src/container.rs#L103) makes it
1. confusing (because why are there (Un)OrderedList, but no list element?)
2. too rigid, because `<li>` elements cannot be created with attributes

**Comment by skubalj** [comment]
Thanks for opening an issue!

The special case for lists was intentional, as it helps to prevent adding `<li>` elements where they don't belong, and ensures that they _are_ used where expected. I initially created this library because I was trying to output HTML, but found that it was too easy to forget brackets, parentheses, and closing tags. By making list types automatically wrap their contents, we make sure that they're not forgotten. 

Regarding point 1, we can probably alleviate some confusion by improving the documentation to tell users that `<li>` tags are generated automatically. I'll look at that before publishing the next release. Regarding point 2, I'd probably like to add the ability to set attributes on list items similar to how they were hacked in for [table rows and cells](https://docs.rs/build_html/latest/build_html/struct.Table.html#method.add_custom_body_row), rather than making it a proper `ContainerType`. As far as I'm aware, list items aren't really meaningful outside of lists. Because of the way lists are currently implemented, hacking that in would be more difficult than for `TableRow`s. (Admittedly, this is due to a lack of future planning on my part when I first created the library)

Balancing the desire for simplicity with the desire for flexibility has been one of the challenges with maintaining this library. To meet these needs, I've been prototyping interfaces for a backwards incompatible v3.0.0 update in my spare time. It will be a while before that is ready though. In the meantime, I might suggest that you use the escape hatches built into the library to implement the functionality you need. That will probably look something like this:

<details>
<summary>Example</summary>

```rust
use build_html::{Html, HtmlContainer};

/// Take the list of attributes and render it out as a string
fn format_attrs<I, S>(iter: I) -> String
where
    I: IntoIterator<Item = (S, S)>,
    S: ToString,
{
    iter.into_iter()
        .map(|(a, b)| format!(r#" {}="{}""#, a.to_string(), b.to_string()))
        .collect::<Vec<_>>()
        .join("")
}

/// A custom `<li>` element
#[derive(Debug, Default)]
struct ListItem {
    attributes: String,
    contents: String,
}

impl ListItem {
    pub fn new<I, S>(attributes: I) -> Self
    where
        I: IntoIterator<Item = (S, S)>,
        S: ToString,
    {
        Self {
            attributes: format_attrs(attributes),
            contents: String::new(),
        }
    }
}

impl Html for ListItem {
    fn to_html_string(&self) -> String {
        format!("<li{}>{}</li>", self.attributes, self.contents)
    }
}

impl HtmlContainer for ListItem {
    fn add_html<H: Html>(&mut self, html: H) {
        self.contents.push_str(&html.to_html_string())
    }
}

/// A custom list element, either `ul` or `ol`
#[derive(Debug)]
struct List {
    ordered: bool,
    attributes: String,
    contents: String,
}

impl List {
    pub fn new<I, S>(ordered: bool, attributes: I) -> Self
    where
        I: IntoIterator<Item = (S, S)>,
        S: ToString,
    {
        Self {
            ordered,
            attributes: format_attrs(attributes),
            contents: String::new(),
        }
    }

    pub fn add_item(&mut self, li: ListItem) {
        self.contents.push_str(li.to_html_string().as_str());
    }

    pub fn with_item(mut self, li: ListItem) -> Self {
        self.add_item(li);
        self
    }
}

impl Html for List {
    fn to_html_string(&self) -> String {
        let tag = if self.ordered { "ol" } else { "ul" };
        format!("<{}{}>{}</{}>", tag, self.attributes, self.contents, tag)
    }
}

/// This implementation of `HTMLContainer` should replicate the behavior of the
/// existing list containers, but opens the possibility of double-wrapping with
/// `<li>`s if you were to pass a `ListItem` as the parameter. You can consider
/// it to be optional.
impl HtmlContainer for List {
    fn add_html<H: Html>(&mut self, html: H) {
        self.contents.push_str(
            ListItem::default()
                .with_html(html)
                .to_html_string()
                .as_str(),
        )
    }
}

#[test]
fn example() {
    let ul = List::new(false, [("id", "my-list")])
        .with_paragraph("abc")
        .with_item(ListItem::new([("id", "li-1")]).with_paragraph("def"))
        .to_html_string();

    assert_eq!(
        r#"<ul id="my-list"><li><p>abc</p></li><li id="li-1"><p>def</p></li></ul>"#,
        ul
    );
}

```

</details>

**Comment by skubalj** [comment]
With the release of v2.5.0, you can now manually make containers and list items as you wish using `HtmlElement`.
