### ISSUE TITLE
Create `<ul>` with `<li>`'s

### ISSUE THREAD

**Issue by 766F6964** [skubalj/build_html#14]
I would like to create the following HTML structure using build_html:
```
 <ul>
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
</ul> 
```
Creating the container, the `<ul>`, is straightforward. However, I could not find any way to create the list items, the `<li>`'s, except by using `with_raw()`, which is not ideal. There is no `.with_list_item`, or something like that?
What is the intended way to create the HTML snippet described above, specifically the `<li>`'s?

**Note:** I am aware a similar issue exists, #10, but from what I understood the focus there was on creating custom attributes for the list elements. Also, I am not sure what has changed since that  discussion.

**Comment by skubalj** [comment]
Thanks for opening an issue!

There's an interesting tension in this library between what I had originally intended --an opinionated and relatively simple way to not forget fiddly tags-- and the complexity and flexibility that people want for the things they're using `build_html` for. In this case, we're covered by my original --somewhat limited-- vision of not forgetting things; the `<li>` tags are added automatically around each child of `<ul>` and `<ol>` containers. (That applies to text, as well as other content like nested containers)

For your example, where you just want raw text inside the `<li>` tags, you can do:
```rust
Container::new(ContainerType::UnorderedList) // <ul>
    .with_raw("Coffee") // <li>Coffee</li>
    .with_raw("Tea")    // <li>Tea</li>
    .with_raw("Milk")   // <li>Milk</li>
    .to_html_string();  // </ul>
```

If you want to wrap your text in another tag to help define its style, you can do that with the other `HtmlContainer` methods:
```rust
Container::new(ContainerType::UnorderedList) <ul>
    .with_paragraph("Coffee") // <li><p>Coffee</p></li>
    .with_paragraph("Tea")    // <li><p>Tea</p></li>
    .with_paragraph("Milk")   // <li><p>Milk</p></li>
    .to_html_string();        // </ul>
```

The issue raised in #10 specifically is that there's no way to manually create `<li>` elements -- they're managed completely automatically. Due to a lack of time and a surplus of projects, I haven't made much progress towards a v3 of this library, so the discussion there is still valid.

**Comment by 766F6964** [comment]
Thanks for the reply. This seems to work fine for single nested tags, but it does not seem to work when we want to nest more than one tag inside an `<li>`.

For example, I am trying to do the following:

```html
<ul>
  <li><div id="AAA">Coffee</div><div id="BBB">Unhealthy</div></li>
  <li><div id="AAA">Tea</dev><div id="BBB">Healthy</div></li>
  <li><div id="AAA">Milk</dev><div id="BBB">Healthy</div></li>
</ul>
```
The problem is, I either get nesting of the divs itself, or each div being wrapped in a separate `<li>`.
Does the API allow for a scenario like the one outlined above?

**Comment by skubalj** [comment]
This is where we go from the original vision which was pretty limited to the harsh reality of the complexities of real use cases. :slightly_smiling_face: 

The functionality to "group" multiple child tags into a single `<li>` element is not natively supported, but you could approximate it by rendering everything out to Strings and passing those to `with_raw`:

```rust
Container::new(ContainerType::UnorderedList)
    .add_raw([
        Container::default().with_attributes([("id", "AAA")]).add_raw("Coffee").to_html_string(),
        Container::default().with_attributes([("id", "BBB")]).add_raw("Unhealthy").to_html_string(),
    ].concat())
```

**Comment by skubalj** [comment]
With the release of v2.5.0, you should now be able to construct this with the new `HtmlElement` type.
